### ISSUE TITLE
Include on Laravel project

### ISSUE THREAD

**Issue by Jackpump** [m1guelpf/ray-js#1] opened 2021-01-13 15:59 UTC
How do i add it to a laravel 8 project using laravel mix?

**Comment by m1guelpf** [comment] 2021-01-15 10:59
You should be able to install it by running `yarn add js-ray` or `npm install js-ray`.

**Comment by builpro** [comment] 2021-01-17 07:25
Sorry, but I imported correctly the packet and  it doesn't work on my Laravel 8 + Vue 2 project.
Could you help me, pls?
![image](https://user-images.githubusercontent.com/63128886/104834058-a6002a00-5862-11eb-8fc3-a4fa18af8c2e.png)

**Comment by m1guelpf** [comment] 2021-01-17 09:35
@builpro hmmm, are you using Babel? Opened #2 to make sure this is not needed in the future.

**Comment by builpro** [comment] 2021-01-17 17:59
> @builpro hmmm, are you using Babel? Opened #2 to make sure this is not needed in the future.

I use laravel-mix (webpack) but I also installed babel and still get the same error

**Comment by Gompje** [comment] 2021-01-20 11:09
I'm having the same issues. Laravel 8 + latest mix. I do have a bunch of diff loaders in my webpack (its a complex app). @m1guelpf is there a L8 project with L-mix that already works out there? (to compare diff) 

I'm happy to contribute but I don't know where to start
At first glance this is my relevant dep list (I think)
```
    "babel-core": "^6.26.3",
    "babel-eslint": "^10.1.0",
    "babel-jest": "^26.6.3",
    "laravel-mix": "^6.0.2",
```

Fyi: there is a mismatch in this repo-name and the actual package name. caused some confusing.

**Comment by hi-reeve** [comment] 2021-01-21 09:56
i got the same error on laravel 8 and the latest mix with vue 3

**Comment by m1guelpf** [comment] 2021-02-01 15:57
We've just released a new version of the package! Could any of you try this again and check if it's still an issue?

**Comment by slovenianGooner** [comment] 2021-02-01 16:33
Installed version 0.0.3 and get this error when trying to import as per documentation:

```
ERROR in ./resources/js/app.js
Module not found: Error: Can't resolve 'js-ray' in '/Users/papezl/Sites/oc/resources/js'
 @ ./resources/js/app.js 49:0-29 50:21-24
```

This is in app.js

```
...
import { ray } from "js-ray";
...
```

**Comment by morrislaptop** [comment] 2021-02-01 17:22
FWIW I'm getting `Error: Cannot find module 'stacktrace-js'` on frontend.

Adding as a local dependency fixed it.

**Comment by m1guelpf** [comment] 2021-02-01 17:34
Tagged another release which should fix @slovenianGooner @morrislaptop's problems!

**Comment by morrislaptop** [comment] 2021-02-01 17:36
@m1guelpf thanks! Is this package intended to work from browser and node contexts? 

Just trying this in Node and I got `Cannot use import statement outside a module`

**Comment by m1guelpf** [comment] 2021-02-01 17:38
@morrislaptop It's intended to work from both the browser and node, but the browser path hasn't been tested as much.

cc @cossou can you take a look at the error?

**Comment by slovenianGooner** [comment] 2021-02-01 17:48
Looks like it works for me - everything build properly. 

Other issue though:

```js
ray({ text: "an object" });
```

shows me this in Ray:

<img width="364" alt="Screenshot 2021-02-01 at 18 47 17" src="https://user-images.githubusercontent.com/1257629/106497229-0f687580-64be-11eb-94d3-46e555c4c67d.png">

**Comment by cossou** [comment] 2021-02-01 17:50
> ```js
> ray({ text: "an object" });
> ```

Yep, run into that error too. Looks like we need a `ray().json({ obj })`

**Comment by cossou** [comment] 2021-02-01 17:53
Just test in a project and I can confirm it works in browser + server 👍🏽

**Comment by m1guelpf** [comment] 2021-02-01 18:01
Closing this, we can open another issue for the JSON helper.

**Closed as completed by m1guelpf** 2021-02-01 18:01 UTC
